// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf0lJJ8WXx0nCOIrnmis8bFHVKFhoWFHM',
    appId: '1:10265668297:web:47fbb13c5a0cdfbc957b18',
    messagingSenderId: '10265668297',
    projectId: 'one-one-70509',
    authDomain: 'one-one-70509.firebaseapp.com',
    storageBucket: 'one-one-70509.appspot.com',
    measurementId: 'G-Z7E1ZLQNXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgRO-59WFI6XFP_zohzijffRhqHi7N86Y',
    appId: '1:10265668297:android:f526ecf9a2a10219957b18',
    messagingSenderId: '10265668297',
    projectId: 'one-one-70509',
    storageBucket: 'one-one-70509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuTE3_nZV5CvyD0WNa_pczmE89fYFvP-M',
    appId: '1:10265668297:ios:a21c9e94007844df957b18',
    messagingSenderId: '10265668297',
    projectId: 'one-one-70509',
    storageBucket: 'one-one-70509.appspot.com',
    iosClientId: '10265668297-ah60jsmps5fa0jjdha48vm7vkcb8sm0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuTE3_nZV5CvyD0WNa_pczmE89fYFvP-M',
    appId: '1:10265668297:ios:a21c9e94007844df957b18',
    messagingSenderId: '10265668297',
    projectId: 'one-one-70509',
    storageBucket: 'one-one-70509.appspot.com',
    iosClientId: '10265668297-ah60jsmps5fa0jjdha48vm7vkcb8sm0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
